input : str = "GACGACAAGTAGCACATGAGTCAGGGTAAGAGAAGCGCACGACTGCACATGGAACCAGGCATTGCGATCTCGTCCGGTCTGGCCTATGTAGAAATCTGCTTATCCTTCATGGGTGGGTAAGACCACAGCAGGAGAAGCATAGGGTTCCTAGTCGACTATGAGGAGCTGCGCATGGTCGGAGCGTCTCGCTCTCGACTCATGCACATGCTGAAAGCTTGACTAGGGTCACGCGTTGTACCGAATTTTTGATACCATTGACATCTAACCGTCTCCCGTATCCAGCCGTCTCCGGGATGCCCAAGATTAGGTTCTATTAACGGGCCCAACTGGTAACGTCCCGCCCCGTAGTCCCAGTCATGATTGACATCCTGGCGAAATCATCTCAGCTCGTGACAGGTGCATGAGTTGTAGGTGCTCCGAGGTTCAACGTCTTCATCGGAGTACCGGGGGAGTTGGTGGTATATGCCCTGGTGGCCGAGTAACTATCTAGATAATTTAAGCGCACCGATGCGAAACCTGGTAAGCAACAGTTTAAGTACTCTCCGGCCATATACTCACACAGACAAGAGGATCACGATTGAGCTCTGGATTGGTATATCGAATACACGCATGTTAAGTACAGGCTTCCCTTATAATCGGCTCCAAACGACCTTGGTTACGTATGCACACGTTGCCAACTATAAACTCGACATTTGCCCAACCGCAAAGATTCAGGCTGTGGCGATCAGACGCTTTAAAGTCCAACTAACCGGAAGTTCAACCAAACTGAGCTACTGGATCTGAGTGGGCTGAGAGCCCTGTCTAAGCAGCGGAATGTCGGGCGGCCCTTGGCGCTCTTGATTTCTTTAATCTAACAGATTTGCGAAATCTAATAGTGAAGACCCGTCCAACGC"

a_counter : int = 0
c_counter : int = 0
g_counter : int = 0
t_counter : int = 0
error_counter : int = 0

for character in input:
    match character:
        case 'A':
            a_counter += 1
        case 'C':
            c_counter += 1
        case 'G':
            g_counter += 1
        case 'T' :
            t_counter += 1
        case _:
            error_counter += 1
    
print(f"{a_counter} {c_counter} {g_counter} {t_counter}")
             